/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.kotlinx.coroutines.core)
    implementation(kotlin("reflect"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "adventofcode.AppKt"
}

tasks.getByName("run", JavaExec::class) {
    standardInput = System.`in`
}

// Task to generate boilerplate for a new day
// Usage: ./gradlew newDay -Pday=5
tasks.register<JavaExec>("newDay") {
    group = "advent of code"
    description = "Generate boilerplate code for a new day. Usage: ./gradlew newDay -Pday=<number>"

    mainClass = "adventofcode.NewDayGeneratorKt"
    classpath = sourceSets["main"].runtimeClasspath
    standardInput = System.`in`

    // Read property at configuration time (compatible with configuration cache)
    val dayNumber = providers.gradleProperty("day")

    argumentProviders.add {
        if (dayNumber.isPresent) {
            listOf(dayNumber.get())
        } else {
            throw GradleException("Please specify a day number with -Pday=<number>")
        }
    }
}

