/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.*


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

//fun main() {
//    println(App().greeting)
//}

fun main() = runBlocking { // Bridges the non-coroutine main to coroutine world
    launch {
        delay(1000L)
        println("World!")
    }
    print("Hello, ")
}